# add by martinec
# Based on:
#  https://github.com/harshjv/travis-ci-latex-pdf
#  https://github.com/SimonWaldherr/HowTo-Deploy-LaTeX-Documents
#  https://gist.github.com/snim2/9160862
#  https://docs.travis-ci.com/user/notifications
os: linux
dist: trusty

# R VM already contains LaTeX
# language: r

# sudo required
sudo: required

# notifications
notifications:
  email:
    recipients:
      - unitex-devel@univ-mlv.fr
    on_success: change
    on_failure: always
  slack:
    secure: QiGkl5HS7YGL2+OZt9slPGH3LDzK9jYSlKdI3WkCXSj9VCkjaLWexwATNXdW/udzZutaJ4m5k+tdRY6LX+Lwn5EnMWmM605+avVfxc7paZxCyVHXlHs6Axqq/kqxEXcybE5A06TA0U/0qnQPnwX1qjToL/vNP8y5+DxoPKn5GvZqA4azOyf8q5bIOFQA24TdiAfrf/V17eNx2IlaVwI5obI5N7bgV8quqBOj7usoDt/IyClDJXpoHKxvW8uYds4o1SyDDs9Rbg/LCBL/1IEO6c43YwSzpbobW9IZ7wa0kdBTk+pcGsC0IormoNyxshgp1EdN234BngbusBZBZb6wFFA39T0wSIR9kiUzzr19isP5/deKgy/cXAiuhK1xAXVvXnuK9xU0nGKxgt8J/Jf9UIip/JhVWyaN5teisVbO3Qe7hS9H0MMMpt9RPL06l3QG7hhw/Tk/gt9iMpx3AMJbRHKVCyAWVzQ61Cp+BY8hu8gXh450hiNisJS6yDhjx4bX8fC859inYND91rd6LlTs/IHpNeovv+8bg7ST1XZ+mH67uLyLadaLTxOYEdVqA1yGqyxPedxJAljloivuXHDGZVkoAY3d3O4ODLTXwl6WuLASDDlV6oxYEyeOV31+x8B8H1o6JHSlGTFow5cYS7u1692ZObNscHRURNvZzpuQ7jA=

before_install:
  - sudo apt-get update && sudo apt-get install -y --no-install-recommends  texlive-latex3 texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-lang-french texlive-latex-recommended latex-cjk-all dvipng xindy chktex
    
install:
  - cd tex
  - ./install-latex-dependencies.sh
  
script:
  - make -f Makefile_EN_utf8
  - mv UnitexManual_EN_utf8.pdf UnitexGramLab-usermanual-en.pdf
  - make -f Makefile_FR_utf8
  - mv UnitexManual_FR_utf8.pdf UnitexGramLab-usermanual-fr.pdf
  - make -f Makefile_ZH_utf8
  - mv UnitexManual_ZH_utf8.pdf UnitexGramLab-usermanual-zh.pdf
  #- chktex -W
  #- chktex -q -n 6 *.tex 2>/dev/null | tee lint.out
  #- test ! -s lint.out

deploy:
  provider: releases
  api_key:
    secure: XU5V/23iB7pz8LmO4Xz7FiQlF/dkjkhdg0W7ZEh3rFYLD70hO+umf++lfkhyUY+7l3iLko9er4SE00aZW0/ZfD21+O+sch9Fnt977BfFcuKKy3DlmLXLOiuHefng3WxlTW75rib4ZFbLEg8e+1tq8vDHKSCuVFd3MDr4e20omI1wufJB9/x+Jm9CuxwzCqpZ3Z04DzQDeTTTce7kEA3ShlBExD0F6g9C2JT1cRs0qgsJVi9RQjLihg9+NFyQR8hpa5Q1HVQNsQmrAJ/RmMyDMuVWhOxeq2mJpRF0oA6YCjp/m+FnLFqmhedxsFev8XX0/ufRnThRwYcKTijKCEcXh4Lc7VqX14Rz8N6SbdejTBBUa/WxSyIg2INJv1DtRAWZrEoIGPm0qwcfc1nHYvx+VYyBCtEZzJPZaAnd27lyApimgXbXXnHSshBHA4TqtEoOYgnp8atjenuRSZsisVlCe4vCp3U9Jb9p9a+X/U6Vwkg7AAtnUntm60OszfWOjamvOuCAmL+8LlMdxyARO3lAW6Q8A6T8DV7uWPH4eOsSFNMVNEMw0jTvgmrC2y2NOqxpjrNOPxtH5VsqKaym9AWeTmEkLifxhja3B+lpl5xWGA8FclKv6xRlPJ2fSHZMocoFW48/APkZ9o3lY4YPIBiiyQ4SKOVUC0QwmSZMqR0/tek=
  file:
    - UnitexGramLab-usermanual-en.pdf
    - UnitexGramLab-usermanual-fr.pdf
    - UnitexGramLab-usermanual-zh.pdf
  skip_cleanup: true
  on:
    repo: UnitexGramLab/unitex-doc-usermanual
    all_branches: true
    tags: true
